package clent1.main;

import clent1.form.Home;
import clent1.login.Enter_into_House;
import clent1.recognition.Recognition;
import clent1.swing.*;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class
Main extends javax.swing.JFrame {

    private Home home;
    Socket_Client socket_client;

    public Main() {
        initComponents();
        home = new Home();
        //setAlwaysOnTop(true);
        EventOpenTheDoor eventOpenTheDoor = new EventOpenTheDoor() {
            @Override
            public void OpenDoor() {
                main.removeAll();
                main.add(home);
                main.revalidate();
                main.repaint();
                Timer timer = new Timer(3000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent arg0) {
                        CloseDoor();
                    }
                });
                timer.setRepeats(false); // Only execute once
                timer.start();

            }

            @Override
            public void CloseDoor() {
                main.removeAll();
                main.add(home_screen_client);
                main.revalidate();
                main.repaint();
            }
        };

        EventOpenTheDoor eventTakePassword = new EventOpenTheDoor() {
            @Override
            public void OpenDoor() {
                main.removeAll();
                main.add(home);
                main.revalidate();
                main.repaint();

            }

            @Override
            public void CloseDoor() {
                main.removeAll();
                main.add(home_screen_client);
                main.revalidate();
                main.repaint();
            }
        };

        enter_into_house.setEventOpenTheDoor(eventOpenTheDoor);
        Socket_Client s=Socket_Client.getInstance();
        s.setEventOpenTheDoor(eventOpenTheDoor);
        home.setEventOpenTheDoor(eventOpenTheDoor);
        Recognition.setEventTakePassword(eventTakePassword);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        home_screen_client = new clent1.login.Home_Screen_Client();
        enter_into_house = new clent1.login.Enter_into_House();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setLayout(new java.awt.BorderLayout());
        main.add(home_screen_client, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 1309, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new open_screen.splashscreen.SplashScreen(null, true,false).setVisible(true);
                new Main().setVisible(true);
            }
        });
    }

    private clent1.login.Home_Screen_Client home_screen_client;
    private clent1.login.Enter_into_House enter_into_house;
    private javax.swing.JPanel main;

    // End of variables declaration//GEN-END:variables
}
